apiVersion: v1 
kind: Service 
metadata: 
  name: app-internal-service
  namespace: devops-cycle-test
spec:
  selector:
    app: devops-cycle-demo-deployment
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8081 
  type: ClusterIP # Default 
